---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.global.namespace}}
    labels:
      pod-security.kubernetes.io/enforce: privileged
      security.openshift.io/scc.podSecurityLabelSync: "false"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openstack
  namespace: {{ .Values.global.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.global.namespace }}