apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.passwordSecret }}
  namespace:  {{ .Values.global.namespace }}
type: "kubernetes.io/storageos"
data:
  AdminPassword: {{ .Values.global.password | b64enc | quote }}
  DbRootPassword: {{ .Values.global.password | b64enc | quote }}
  DatabasePassword: {{ .Values.global.password | b64enc | quote }}
  KeystoneDatabasePassword: {{ .Values.global.password | b64enc | quote }}
  PlacementPassword: {{ .Values.global.password | b64enc | quote }}
  PlacementDatabasePassword: {{ .Values.global.password | b64enc | quote }}